CREATE TABLE IF NOT EXISTS `user_account`(
    `username` VARCHAR(255) NOT NULL,
    `email` VARCHAR(255) NOT NULL,
    `password` MEDIUMTEXT NOT NULL,
    `role` TINYINT NOT NULL,
    `created_at` DATETIME NOT NULL,
    CONSTRAINT PK_USERS_IDUSER PRIMARY KEY (`username`),
    CONSTRAINT UK_USERS_EMAIL UNIQUE (`email`(255))
) ENGINE InnoDB;