CREATE TABLE `user_account`(
    `id_user` BIGINT AUTO_INCREMENT,
    `username` MEDIUMTEXT NOT NULL,
    `email` MEDIUMTEXT NOT NULL,
    `password` MEDIUMTEXT NOT NULL,
    `role` TINYINT NOT NULL,
    `created_at` DATETIME NOT NULL,
    CONSTRAINT PK_USERS_IDUSER PRIMARY KEY (`id_user`),
    CONSTRAINT UK_USERS_EMAIL UNIQUE (`email`(255)),
    CONSTRAINT UK_USERS_USERNAME UNIQUE (`username`(255))
) ENGINE InnoDB;